# Generated by Django 4.2.5 on 2025-03-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeNo', models.AutoField(primary_key=True, serialize=False)),
                ('post_username', models.CharField(max_length=255)),
                ('user_no', models.IntegerField()),
                ('recipe', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
