# Generated by Django 4.2.5 on 2025-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_recipe_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.CharField(max_length=50, unique=True)),
                ('size', models.FloatField(default=50)),
                ('position_x', models.FloatField(default=100)),
                ('position_y', models.FloatField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
