# Generated by Django 4.2.5 on 2025-03-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_buttonconfig_delete_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonconfig',
            name='button_id',
        ),
        migrations.RemoveField(
            model_name='buttonconfig',
            name='size',
        ),
        migrations.AddField(
            model_name='buttonconfig',
            name='height',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='buttonconfig',
            name='width',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='buttonconfig',
            name='position_x',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='buttonconfig',
            name='position_y',
            field=models.IntegerField(default=50),
        ),
    ]
